### PR TITLE
Revert "Adding check for not notifying current client about its own patc...

### PR DESCRIPTION
**Pull request by danbev**
...h"

This reverts commit 9f59e0d0fc85cccc282cf8ea4e5d4a6725dd89cd.
Jira: https://issues.jboss.org/browse/AGSYNC-1

### CODE REVIEW

**Comment by danbev** [comment]
@cvasilak Would you mind doing a review and testing this with the Android client and also with the new ios client. It think this will "solve" https://issues.jboss.org/browse/AGSYNC-44. I'll revisit this later. I've added a comment to [AGSYNC-1](https://issues.jboss.org/browse/AGSYNC-1) with some more details about the problem found.

**Comment by corinnekrych** [comment]
@cvasilak @danbev I'll look too :eyes:

**Comment by danbev** [comment]
@corinnekrych awesome, thanks!

**Comment by cvasilak** [comment]
@danbev tested with iOS/android/JS and worked great :+1:

**Comment by danbev** [comment]
@corinnekrych Did you get a chance to review this as well?

**Comment by corinnekrych** [comment]
:eyes: looking at it this mroning

**Comment by corinnekrych** [comment]
+1 on reverting the change
tested with one ios version deployed on device + one version on simulator
on master => 2nd patch issued doesn't get patched
on revert-agsync-1 => doc get correctly patched

**Comment by danbev** [comment]
@corinnekrych @cvasilak Thanks for reviewing!

**Pull request merged**
