### PR TITLE
Updating main README.me to uses the new project doc template.

### PR DESCRIPTION
**Pull request by danbev**
Jira:
https://issues.jboss.org/browse/AGSYNC-33

### CODE REVIEW

**Comment by danbev** [comment]
@lfryc Would you mind reviewing?

**Comment by lfryc** [comment]
Looks great, @danbev 

Just tiny issue:

````
...Differential Synchonrization ,by Neil Fraser...
````

the `,` is wrongly placed.

**Comment by danbev** [comment]
@lfryc Ah, let me fix that. Thx

**Comment by lfryc** [comment]
:+1: merging

**Comment by danbev** [comment]
Merged as 48c9719. Thanks @lfryc!

**Pull request closed without merging**
