### PR TITLE
Removing System.out.println "logging" statements.

### PR DESCRIPTION
**Pull request by danbev**

### CODE REVIEW

**Comment by danbev** [comment]
@cvasilak @danielpassos Would you guys mind taking a look? It is enough to build the project using ```mvn clean install```.

**Comment by matzew** [comment]
what about here: https://github.com/aerogear/aerogear-sync-server/blob/master/client/client-netty/src/main/java/org/jboss/aerogear/sync/client/netty/SyncClient.java#L96

or https://github.com/aerogear/aerogear-sync-server/blob/master/server/server-netty/src/main/java/org/jboss/aerogear/sync/server/netty/DiffMatchPatchSyncServer.java#L75

**Comment by danbev** [comment]
@matzew Sorry, I just noticed those ones. I've done a grep and now removed the remaining ones as well.

**Comment by danbev** [comment]
@matzew Sorry to bother you again but I'd like to merge this. Would you say you are +1 on it?

**Comment by matzew** [comment]
:+1:

**Comment by danbev** [comment]
@matzew Thanks!
Merged as 52b26f0e3d43b807e94b891e49afd884ebf38010

**Pull request closed without merging**
