### PR TITLE
Change Netty version to 4.1.0.beta4-SNAPSHOT.

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
We are currently using version 5.0.0.Alpha2-SNAPSHOT. But to release we
need a non-snapshot version. There will be a 4.1.0.beta4 release shortly
and we should update our code to make sure it work with that version.
This will make it easy for us to change to the non-snapshot version once
it is available.

Modifications:
Updated the version in the pom.xml and make modifications required for
the difference in Netty code base between 5.0.0 and 4.1.

Result:
Everything works as before and we'll be able to switch to 4.1.0.beta4
when it is available.

JIRA:
https://issues.jboss.org/browse/AGSYNC-47

### CODE REVIEW

**Comment by danbev** [comment]
@cvasilak Would you mind to review? 

To test
1. ```mvn clean install```
2. Start the [JsonPatchSyncServer](https://github.com/aerogear/aerogear-sync-server/tree/master/server/server-netty#jsonpatchsyncserver)
3. Build and try the [Android demo](https://github.com/danbev/android-diffsync-demo/tree/json-patch-sync-server-example#building-and-testing)

**Comment by danbev** [comment]
Sorry, the version is incorrect which is why the build is failing. Will push a fix for this shortly.

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
was able to build and run. the Android app got connected against the sync-server.

**Comment by cvasilak** [comment]
build/run succeeded and connected using iOS/Android/JS :+1:

**Comment by danbev** [comment]
Merged as 62c00c0e6fae230e388b2067bb11f9738c80392f

**Pull request closed without merging**
