### PR TITLE
Fixing incorrect usage of backup version in ClientSyncEngine.

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
Currently when restore of a backup shadow is done the ClientSyncEngine
would use the backups version, which on the client side represents the
servers version. It would use this version, that is the server version,
to create a new BackupShadowDocument. This is a bug.

Modifications:
The code can be simplified and instead of creating a new
BackupShadowDocument instance, the ShadowDocument that the backup holds
can be used instead.

I've also added some additional comments to the tests to clarify why
some changes were made to them.

Result:
Simpler code code and the bug does not exist anymore.

Jira: https://issues.jboss.org/browse/AGSYNC-26

### CODE REVIEW

**Comment by danbev** [comment]
@lfryc Would you mind reviewing this when you get a chance?

**Comment by lfryc** [comment]
Sure, taking a :eyes: ..

**Comment by danbev** [comment]
@lfryc After you brought up the issue and provided a different test case, I've updated the code to use you version of the test, slightly modified. The version in https://github.com/danbev/aerogear-sync-server/commit/7812adc7f0b514b8fab1516f1cf67d0d82817c90 will favour the servers version when a restore has been performed. I've commented the test and code so hopefully this can be followed. Would you mind doing a second review of this and see what you think?

**Comment by lfryc** [comment]
Thanks @danbev  for looking into that. I'm reviewing the changes right now!

**Comment by lfryc** [comment]
Hey @danbev , I had a little bit different behavior in mind:

when client sends changes to an outdated version of the shadow (it is not equivalent to server document),

the server shadow should be patched seamlessly,

while document should be patched on best-effort basis.

----

The test scenario shows non-conflicting changes (changes in two different branches of JSON structure), but still the server document version is a result.

I believe the result should be merged version instead, such as in the test case outlined by this change:
https://github.com/lfryc/aerogear-sync-server/commit/e77af19787547a5eb400067e6ca9ae42b97694b8#diff-5646796182358776e8464aff4c94155cR319

**Comment by danbev** [comment]
@lfryc A yes that makes sense. I've taken another stab at this, and rebased in the process but kept the commits separate so the last commit is the one of interest.

**Comment by danbev** [comment]
@lfryc Like discussed on IRC lets move issue with the correct backup handling to a future jira. I've reset this PR and rebased it.

**Comment by lfryc** [comment]
:eyes: once more...

**Comment by lfryc** [comment]
:+1: Looks good @danbev 

Thanks for all the hard work here!

----

Can I merge this or do you want more :eyes:  to review?

**Comment by danbev** [comment]
@lfryc Please merge it. You might need to rebase it. Thanks!

**Comment by lfryc** [comment]
Merged: https://github.com/aerogear/aerogear-sync-server/commit/ddb83fa01805df799e5de77d8849702776e35184

**Comment by lfryc** [comment]
Created https://issues.jboss.org/browse/AGSYNC-49

**Pull request closed without merging**
